# Generated by Django 5.2.4 on 2025-08-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('на согласовании', 'На согласовании'), ('одобрен', 'Одобрен'), ('на доработке', 'На доработке')], default='на согласовании', max_length=20)),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='Комментарий руководителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
        ),
    ]
