# Generated by Django 5.2.4 on 2025-08-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_document_creator_document_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type_choices',
            field=models.CharField(blank=True, choices=[('Исходящий', 'Исходящий'), ('Входящий', 'Входящий')], max_length=20, null=True, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Краткое содержание'),
        ),
    ]
