# Generated by Django 5.2.4 on 2025-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_documentactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_choices',
            field=models.CharField(blank=True, choices=[('Исходящий', 'Исходящий'), ('Входящий', 'Входящий'), ('Внутренний', 'Внутренний')], max_length=20, null=True, verbose_name='Тип документа'),
        ),
    ]
