# Generated by Django 5.2.4 on 2025-07-23 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер')),
                ('title', models.CharField(max_length=255, verbose_name='Тема документа')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('sender', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('received_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('file', models.FileField(upload_to='incoming/', verbose_name='Файл документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировал')),
            ],
        ),
    ]
