# Generated by Django 5.2.4 on 2025-07-23 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_incomingdocument_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('review', 'На рассмотрении'), ('approved', 'Согласован'), ('completed', 'Исполнен')], default='review', max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий/резолюция')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='documents.incomingdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
