# Generated by Django 5.2.4 on 2025-07-23 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст документа')),
                ('recipient', models.CharField(max_length=255, verbose_name='Получатель')),
                ('file', models.FileField(blank=True, null=True, upload_to='outgoing/', verbose_name='Приложение')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('sent', 'Отправлен')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
